import os
import json
import google.generativeai as genai
from typing import List, Dict

class AIProcessor:
    """Dokari AI Processor for documentation generation and Q&A chat using Google Gemini with fallback models"""
    
    def __init__(self):
        # Configure API key from environment
        api_key = os.getenv('GEMINI_API_KEY') or os.getenv('OPENAI_API_KEY')
        genai.configure(api_key=api_key)
        self.system_prompt = "You are Dokari, an expert technical documentation writer specializing in generating clean, comprehensive, and professional documentation without icons or emojis."
        # Ordered list of fallback models to cycle through on quota errors (429)
        self.models_fallback = [
            "gemini-2.5-flash",
            "gemini-2.5-flash-lite",
            "gemini-3.1-flash-lite",
            "gemini-flash-lite-latest",
            "gemini-3-flash-preview"
        ]

    def _generate_content_with_fallback(self, contents, system_instruction=None, generation_config=None):
        """Generates content using a list of fallback models if quota is exceeded"""
        last_exception = None
        for model_name in self.models_fallback:
            try:
                model = genai.GenerativeModel(
                    model_name=model_name,
                    system_instruction=system_instruction
                )
                config = generation_config or {}
                response = model.generate_content(contents, generation_config=config)
                return response
            except Exception as e:
                err_str = str(e)
                # Check for quota or rate limit errors
                if "429" in err_str or "quota" in err_str.lower() or "limit" in err_str.lower():
                    print(f"Model {model_name} rate limited or quota exceeded. Trying fallback... Error: {err_str[:150]}")
                    last_exception = e
                    continue
                else:
                    # For other types of errors, raise immediately
                    raise e
        # If all models failed, raise the last exception
        if last_exception:
            raise last_exception
        raise Exception("No fallback models succeeded")
    
    def generate_api_documentation(self, files_content: List[Dict]) -> str:
        """Generate API documentation from code files"""
        prompt = self._create_api_doc_prompt(files_content)
        
        try:
            response = self._generate_content_with_fallback(
                prompt,
                system_instruction=self.system_prompt
            )
            return f"""# Dokari Generated API Documentation

{response.text}

---
*Generated by Dokari - AI-Powered Technical Documentation Companion*
"""
        except Exception as e:
            return f"""# API Documentation

## Overview
This documentation was generated by Dokari.

## Endpoints
Documentation generation encountered an issue. Please check your Gemini API configuration.

**Error:** {str(e)}

---
*Dokari - Making documentation easy*
"""
    
    def generate_readme(self, project_info: Dict, files_summary: str) -> str:
        """Generate README.md content"""
        prompt = f"""
Project Name: {project_info.get('name', 'Dokari Project')}
Description: {project_info.get('description', 'Generated by Dokari')}

Files Structure:
{files_summary}

Generate a comprehensive README.md with:
1. Project title and description
2. Features
3. Installation instructions
4. Usage examples
5. API endpoints (if applicable)
6. Configuration
7. Contributing guidelines
8. License
Do not include any icons or emojis in the markdown response.
"""
        
        try:
            response = self._generate_content_with_fallback(
                prompt,
                system_instruction=self.system_prompt
            )
            return f"""{response.text}

---
## Documentation Status

This README was automatically generated by Dokari
Last updated: {self._get_current_timestamp()}
For manual edits, modify this file directly
"""
        except Exception as e:
            return f"""# {project_info.get('name', 'Dokari Project')}

## Description
{project_info.get('description', 'A project documented with Dokari')}

## Quick Start
Documentation generation encountered an issue. Please check your configuration.

**Error:** {str(e)}

---
*Generated with Dokari - AI Documentation Generator*
"""

    def generate_chat_answer(self, files_content: List[Dict], question: str, history: List[Dict]) -> str:
        """Answer code-related Q&A chat questions based on uploaded files context"""
        prompt = "You are the Dokari AI Companion, an expert software developer. Answer questions about the following project files.\n\nFiles Content:\n"
        for file in files_content[:5]:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"--- File: {fname} ---\n"
            prompt += file.get('content', '')[:1500]
            prompt += "\n"
        
        system_prompt = "You are the Dokari AI Companion, a helpful and precise technical assistant. Answer the user's questions based on the provided project files context. Do not use icons or emojis in your answers."
        
        # Build contents structure for Gemini
        contents = []
        # Add files context first
        contents.append({"role": "user", "parts": [prompt]})
        contents.append({"role": "model", "parts": ["I have loaded the files context. How can I help you explain this codebase?"]})
        
        # Add history
        for msg in history[-6:]:
            role = "model" if msg['sender'] == 'ai' else "user"
            contents.append({"role": role, "parts": [msg['text']]})
            
        # Add current question
        contents.append({"role": "user", "parts": [question]})
        
        try:
            response = self._generate_content_with_fallback(
                contents,
                system_instruction=system_prompt
            )
            return response.text
        except Exception as e:
            return f"Chat request encountered an error: {str(e)}"

    def analyze_doc_health(self, files_content: List[Dict]) -> Dict:
        """Analyze the documentation coverage of files and return score + suggestions"""
        if not files_content:
            return {
                "score": 0,
                "suggestions": ["No files uploaded yet. Upload files to calculate your Dokari Health Score."]
            }
            
        prompt = "Analyze the documentation quality of these source files. Evaluate comment densities, docstring existences, class/method explanations, and clarity. Return ONLY a valid JSON object with the keys 'score' (an integer from 0 to 100) and 'suggestions' (a list of 2 to 4 concise technical recommendations on what documentation to add or improve, e.g., 'Add class docstring to main.py:Calculator'). Do not include any markdown fences or extra text, just the raw JSON. Do not use any icons or emojis.\n\nFiles:\n"
        for file in files_content[:5]:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"--- File: {fname} ---\n"
            prompt += file.get('content', '')[:1200]
            prompt += "\n"
            
        try:
            # Enforce JSON mime-type dynamically via Gemini config
            response = self._generate_content_with_fallback(
                prompt,
                generation_config={"response_mime_type": "application/json"}
            )
            
            raw_content = response.text.strip()
            data = json.loads(raw_content)
            return {
                "score": int(data.get("score", 50)),
                "suggestions": list(data.get("suggestions", ["Improve method documentation"]))
            }
        except Exception as e:
            error_log = f"Failed to analyze doc health: {str(e)}"
            print(error_log)
            return {
                "score": 50,
                "suggestions": ["Failed to run AI static analysis. Check Gemini configuration."]
            }
    
    def _create_api_doc_prompt(self, files_content: List[Dict]) -> str:
        """Create prompt for API documentation"""
        prompt = """Analyze the following code and generate comprehensive API documentation in markdown format. Do not use icons or emojis.
Focus on:
- Clear endpoint descriptions
- Request/response examples
- Authentication methods
- Error handling
- Rate limiting

Code files to analyze:
"""
        
        for file in files_content[:5]:  # Limit to first 5 files
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"\n### File: {fname}\n```\n"
            prompt += file.get('content', '')[:1000]  # Limit content length
            prompt += "\n```\n"
        
        prompt += "\nGenerate well-structured API documentation based on the above code."
        return prompt
    
    def _get_current_timestamp(self) -> str:
        """Get current timestamp for documentation"""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")