import openai
import json
from typing import List, Dict

class AIProcessor:
    """DocForge AI Processor for documentation generation"""
    
    def __init__(self):
        self.model = "gpt-3.5-turbo"
        self.system_prompt = "You are DocForge, an expert technical documentation writer specializing in generating clean, comprehensive, and professional documentation."
    
    def generate_api_documentation(self, files_content: List[Dict]) -> str:
        """Generate API documentation from code files"""
        prompt = self._create_api_doc_prompt(files_content)
        
        try:
            response = openai.ChatCompletion.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.system_prompt},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=2000
            )
            
            return f"""# DocForge Generated API Documentation

{response.choices[0].message.content}

---
*Generated by DocForge - AI-Powered Documentation Generator*
"""
        except Exception as e:
            return f"""# API Documentation

## Overview
This documentation was generated by DocForge.

## Endpoints
Documentation generation encountered an issue. Please check your OpenAI API configuration.

**Error:** {str(e)}

---
*DocForge - Making documentation easy*
"""
    
    def generate_readme(self, project_info: Dict, files_summary: str) -> str:
        """Generate README.md content"""
        prompt = f"""
Project Name: {project_info.get('name', 'DocForge Project')}
Description: {project_info.get('description', 'Generated by DocForge')}

Files Structure:
{files_summary}

Generate a comprehensive README.md with:
1. Project title and description
2. Features
3. Installation instructions
4. Usage examples
5. API endpoints (if applicable)
6. Configuration
7. Contributing guidelines
8. License
"""
        
        try:
            response = openai.ChatCompletion.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.system_prompt},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.4,
                max_tokens=2500
            )
            
            return f"""{response.choices[0].message.content}

---
## Documentation Status

✅ This README was automatically generated by **DocForge**
🔄 Last updated: {self._get_current_timestamp()}
📝 For manual edits, modify this file directly
"""
        except Exception as e:
            return f"""# {project_info.get('name', 'DocForge Project')}

## Description
{project_info.get('description', 'A project documented with DocForge')}

## Quick Start
Documentation generation encountered an issue. Please check your configuration.

**Error:** {str(e)}

---
*Generated with DocForge - AI Documentation Generator*
"""
    
    def _create_api_doc_prompt(self, files_content: List[Dict]) -> str:
        """Create prompt for API documentation"""
        prompt = """Analyze the following code and generate comprehensive API documentation in markdown format.
Focus on:
- Clear endpoint descriptions
- Request/response examples
- Authentication methods
- Error handling
- Rate limiting

Code files to analyze:
"""
        
        for file in files_content[:5]:  # Limit to first 5 files
            prompt += f"\n### File: {file['filename']}\n```\n"
            prompt += file['content'][:1000]  # Limit content length
            prompt += "\n```\n"
        
        prompt += "\nGenerate well-structured API documentation based on the above code."
        return prompt
    
    def _get_current_timestamp(self) -> str:
        """Get current timestamp for documentation"""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")